### ISSUE TITLE
Produtos

### ISSUE THREAD

**Issue by wendellunny** [rnads/casa-de-carnes#1]
### Todos os Produtos
 - [ ] Telas que mostram os produtos
 - [ ] Funções que buscam da base origem (Seja um .json ou um backend em laravel)
 - [ ] states que armazenam esses dados e fazem a a alteração na renderização do aplicativo
 - [ ] Paginação
 - [ ] Mecanismo de Busca

### Produto Selecionado
- [ ] Tela que mostra os dados do produto
- [ ] Funções que buscam da base
- [ ] states que armazena esses dados e fazem a renderização no aplicativo

###Comprar
- [ ] Redirecionar pra pagina de pagamento
